try {
    timeout(time: 25, unit: 'MINUTES') {
        properties([
            parameters([
                string(name: 'BRANCH', defaultValue: 'master', description: 'Branch')
            ])
        ])
        node('jenkins-node14') {
            container('npm') {
                env.SUPER_VERSION = ''
                stage("Checkout") {
                    cleanWs deleteDirs: true, notFailBuild: true
                    res_branch = env.GERRIT_BRANCH ? env.GERRIT_BRANCH : env.BRANCH
                    echo res_branch
                    git url: 'https://auto_epm-dce_ci@gerrit.delivery.epam.com/a/table-component', branch: res_branch, credentialsId: 'auto-epm-dce-ci-gerrit'
                    }
                withNPM(npmrcConfig:'npm-dce') {
                    stage('Preparation') {
                        sh "npm config set userconfig $WORKSPACE/.npmrc"
                        sh "npm run ci_stage1"
                        version = sh returnStdout: true, script: 'node -pe "require(\'./package.json\').version"'
                        version = version.tokenize('.')[0..1] + "${env.BUILD_ID}"
                        super_version = version.join(".")
                        print super_version
                        env.SUPER_VERSION = super_version
                        sh "npm version $super_version --no-git-tag-version"
                    }
                    stage('Build') {
                        sh "npm run ci_stage2"
                        sh "cp -r ./web_build ./core-env/core_nginx/"
                    }
                }
            }
            container('docker') {
                stage('Publish') {
                    sh """
                        docker build -t harbor.delivery.epam.com/spectrum/table_component:${SUPER_VERSION} ./core-env/core_nginx && \
                        docker push harbor.delivery.epam.com/spectrum/table_component:${SUPER_VERSION}
                    """
                }
            }
        }
    }
}
catch (err) {
    echo "in catch block"
    echo "Caught: ${err}"
    currentBuild.result = 'FAILURE'
    throw err
}
