try {
    timeout(time: 25, unit: 'MINUTES') {
        properties([
            parameters([
                string(name: 'BRANCH', defaultValue: 'master', description: 'Branch')
            ])
        ])
        node('jenkins-node14') {
            container('npm') {
                env.VERSION = ''
                stage("Checkout") {
                    cleanWs deleteDirs: true, notFailBuild: true
                    res_branch = env.GERRIT_BRANCH ? env.GERRIT_BRANCH : env.BRANCH
                    echo res_branch
                    git url: 'https://auto_epm-dce_ci@gerrit.delivery.epam.com/a/table-component', branch: res_branch, credentialsId: 'auto-epm-dce-ci-gerrit'
                    }
                withNPM(npmrcConfig:'npm-dce') {
                    stage('Build') {
                        sh "npm config set userconfig $WORKSPACE/.npmrc"
                        sh "npm i && npm run build"
                        sh "npm run storybook:build"
                        sh "cp -r ./web_build ./core-env/core_nginx/"
                    }
                    stage('Version') {
                        if(res_branch == 'qa'){
                            sh "npm run version:stable"
                            sh "npm run version:alpha"
                        }

                        version = sh returnStdout: true, script: 'node -pe "require(\'./package.json\').version" | tr -d \'\\n\' | sed "s/alpha\\.\\([0-9]*\\)$/alpha.${env.BUILD_ID}/"'
                        sh "npm version $version --no-git-tag-version"
                        env.VERSION = version
                    }
                    stage('Publish Artifact') {
                        sh "npm run publish"
                    }
                }
                currentBuild.description = "Version '${env.VERSION}' Branch '${res_branch}'"
            }
            container('docker') {
                stage('Publish Docker Image') {
                    sh """
                        docker build -t harbor.delivery.epam.com/spectrum/table_component:${VERSION} ./core-env/core_nginx && \
                        docker push harbor.delivery.epam.com/spectrum/table_component:${VERSION}
                    """
                }
            }
        }
    }
}
catch (err) {
    echo "in catch block"
    echo "Caught: ${err}"
    currentBuild.result = 'FAILURE'
    throw err
}
